### PR TITLE
Feature/create splash screen

### PR DESCRIPTION
**Pull request by Breens-Mbaka**
Hi @JoelKanyi I created the Splash Screen for both light mode and dark mode when a user enables dark theme in the phone settings. Here is a [demo](https://drive.google.com/file/d/1Wy263P5wa94lhVrin6AMedxntXhjOssS/view?usp=sharing) of it

### CODE REVIEW

**Comment by JoelKanyi** [comment]
Thank you @Breens-Mbaka let me review it and merge it 🍻

**Comment by Breens-Mbaka** [comment]
@JoelKanyi you can also try testing with other Android versions and see how it performs. I've so far tried API level 33 and it work well. But on API 28(Pixel) I don't know if its because of the emulator but dark theme on the phone settings is not being enabled thus can't be able to see dark mode splash screen(I think its an emulator issue not sure though)

**Review by JoelKanyi — APPROVED** [review]

**Comment by JoelKanyi** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     com.kanyideveloper.mealtime.app-mergeReleaseResources-75:/values/values.xml:1858: error: resource color/cardview_light_background (aka com.kanyideveloper.mealtime:color/cardview_light_background) not found.
     com.kanyideveloper.mealtime.app-mergeReleaseResources-75:/values/values.xml:1858: error: resource color/cardview_light_background (aka com.kanyideveloper.mealtime:color/cardview_light_background) not found.
     error: failed linking references.
```

**Comment by JoelKanyi** [comment]
Try `./gradlew build` on your machine and let me know

**Pull request merged**
